theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
collections:
  library:
    output: true
url: "https://syn.culture404.com/"
domain: "ItsVanAken.com"
baseurl: "/"
title: Culture 404 News
description: Leading Video @GameInformer || 3D Artist || Game Dev || Musician || Multiplayer Sicko 

summary: Defending Gamers Aagainst Culture Warriors
navbar_title: Culture 404 News
twitter_handle: ""
image: "/path/to/img.jpg"
theme_color: "#ffffff"
color: "#002a86"
display_wallet: false
paginate: 10
paginate_path: "/news/page_:num/" 
