theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
collections:
  library:
    output: true
url: "https://syn.culture404.com/"
domain: "syn.Culture404.com"
baseurl: "/"
title: Syn Inquisition
description: Leading an Inqusition into Journalism through Gamification of factchecking, news finding, and website building and management

summary: Questioning Radical Culture Zealots 
navbar_title: Syn Inquisition
twitter_handle: ""
image: "/path/to/img.jpg"
theme_color: "#ffffff"
color: "#002a86"
display_wallet: false
paginate: 10
paginate_path: "/news/page_:num/" 
